#!/usr/bin/env php
<?php
/**
 * thinkphp v5 脚手架创建工具
 */
//读取相关程序
require __DIR__."/src/defines.php";
require __DIR__."/src/autoload.php";
require __DIR__."/vendor/autoload.php";

//设置命令
$cmd = new \Commando\Command();

$cmd->option()
    ->description('A command line toolit to build MVC scaffold for thinkphp v5.*');

//配置文件
$cmd->option('c')
    ->aka('config')
    ->describedAs('define a configuration file, default is : ./src/config.php')
    ->default('./src/config.php')
    ->map(function ($config) {
        return $config;
    });

//项目
$cmd->option('d')
    ->aka('data')
    ->describedAs('define a project data file')
    ->default('./sample/forge.php')
    ->map(function ($data) {
        return $data;
    });

//创建动作
$cmd->option('a')
    ->aka('actions')
    ->describedAs('define build actions, all|mvc|copy')
    ->default('all')
    ->map(function ($actions) {
        return $actions;
    });

//目标路径
$cmd->option('t')
    ->aka('target')
    ->describedAs('define a target directory, default is : ' . TAR_ROOT_PATH)
    ->default(TAR_ROOT_PATH)
    ->map(function ($target) {
        return $target;
    });

//进行创建
$builder = new \thinkbuilder\Builder();
$builder->setConfigFromFile($cmd['config']);
$builder->setDataFromFile($cmd['data']);
$builder->setTargetPath($cmd['target']);
$builder->build();
