#!/usr/bin/env php
<?php
/**
 * thinkphp v5 脚手架创建工具
 */

/**
 * TODO v2.0.0 处理流程
 * 定义全局常量
 * 装载程序代码
 * 处理命令行参数
 * 初始化并运行程序
 */
/* 定义全局常量 */
define('SRC_PATH', __DIR__ . '/src');
define('PACKAGE_PATH', __DIR__ . '/pkg');
define('TAR_ROOT_PATH', __DIR__ . '/deploy');
define('APP_PATH', 'applications');
define('DBFILE_PATH', 'database');
define('PROFILE_PATH', 'profile');
define('PUB_PATH', 'public');
define('CONSOLE_PATH', 'console');
define('VERSION', '1.4.0');

/* 装载程序代码 */
require __DIR__ . "/src/autoload.php";

/* 自动运行 composer 下载安装第三方程序 */
if (!file_exists(__DIR__ . "/vendor/autoload.php")) shell_exec('composer update');
require __DIR__ . "/vendor/autoload.php";

//设置命令
$cmd = new \Commando\Command();

$cmd->option()
    ->description('A command line toolkit to build MVC scaffold for thinkphp v5.*');

//配置文件
$cmd->option('c')
    ->aka('config')
    ->describedAs('define a configuration file, default is : ./src/config.php')
    ->default(__DIR__ . '/src/config.php')
    ->map(function ($config) {
        return $config;
    });

//项目
$cmd->option('d')
    ->aka('data')
    ->describedAs('define a project data file')
    ->default(__DIR__ . '/sample/sample.php')
    ->map(function ($data) {
        return $data;
    });

//目标路径
$cmd->option('t')
    ->aka('target')
    ->describedAs('define a target directory, default is : ' . TAR_ROOT_PATH)
    ->default(TAR_ROOT_PATH)
    ->map(function ($target) {
        return $target;
    });

//资源路径
$cmd->option('a')
    ->aka('assets')
    ->describedAs('define a assets directory, default is : ' . TAR_ROOT_PATH)
    ->default(__DIR__ . '/assets')
    ->map(function ($assets) {
        define('ASSETS_PATH', $assets);
        define('TMPL_PATH', $assets . '/template');
        return $assets;
    });


//进行创建
$app = new \thinkbuilder\Application([
    'config' => $cmd['config'],
    'data' => $cmd['data'],
    'target' => $cmd['target']
]);
$app->run();
