#!/usr/bin/env php
<?php
/**
 * thinkphp v5 脚手架创建工具
 */
//读取相关程序
require __DIR__ . "/src/defines.php";
require __DIR__ . "/src/autoload.php";

if (!file_exists(__DIR__ . "/vendor/autoload.php")) shell_exec('composer update');
require __DIR__ . "/vendor/autoload.php";

//设置命令
$cmd = new \Commando\Command();

$cmd->option()
    ->description('A command line toolit to build MVC scaffold for thinkphp v5.*');

//配置文件
$cmd->option('c')
    ->aka('config')
    ->describedAs('define a configuration file, default is : ./src/config.php')
    ->default('./src/config.php')
    ->map(function ($config) {
        return $config;
    });

//项目
$cmd->option('d')
    ->aka('data')
    ->describedAs('define a project data file')
    ->default('./sample/sample.php')
    ->map(function ($data) {
        return $data;
    });

//目标路径
$cmd->option('t')
    ->aka('target')
    ->describedAs('define a target directory, default is : ' . TAR_ROOT_PATH)
    ->default(TAR_ROOT_PATH)
    ->map(function ($target) {
        return $target;
    });

//进行创建
$builder = new \thinkbuilder\Builder([
    'config' => $cmd['config'],
    'data' => $cmd['data'],
    'target' => $cmd['target'],
    'repository' => $cmd['repository'],
]);
$builder->build();
