#!/usr/bin/env php
<?php
/**
 * wa-craft/generator-php 
 */

/**
 * TODO v2.0.0 处理流程
 * 定义全局常量
 * 装载程序代码
 * 处理命令行参数
 * 初始化并运行程序
 * 增加中间件
 * 增加事件
 * 修改命令行方式
 */
/* 定义全局常量 */
define('SRC_PATH', __DIR__ . '/src');
define('PACKAGE_PATH', __DIR__ . '/pkg');
define('TAR_ROOT_PATH', __DIR__ . '/deploy');
define('APP_PATH', 'webapp/app');
define('DBFILE_PATH', 'db');
define('PROFILE_PATH', 'etc/nginx');
define('PUB_PATH', 'webapp/public');
define('CONFIG_PATH', 'webapp/config');
define('VIEW_PATH', 'webapp/view');
define('VERSION', '3.0.0 alpha1');
define('ASSETS_PATH', __DIR__ . '/assets');
define('TMPL_PATH', ASSETS_PATH . '/template');

/* from v3.0.0 */
define('BACKEND_PATH','/backend');
define('FRONTEND_PATH','/backend');
define('COMMANDLINE_PATH','/backend');
define('OPERATION_PATH','/backend');
define('DOCUMENT_PATH','/backend');
define('SCHEMA_PATH','/backend');

/* 装载程序代码 */

/* 自动运行 composer 下载安装第三方程序 */
if (!file_exists(__DIR__ . "/vendor/autoload.php"))
    shell_exec('composer update');
require __DIR__ . "/vendor/autoload.php";

//设置命令
$cmd = new \Commando\Command();

$cmd->option()
    ->description('A command line toolkit to build MVC scaffold for thinkphp v6.*');

//配置文件
$cmd->option('c')
    ->aka('config')
    ->describedAs('define a configuration file, default is : ./src/config.php')
    ->default(__DIR__ . '/src/config.php')
    ->map(function ($config) {
        return $config;
    });

//项目
$cmd->option('d')
    ->aka('data')
    ->describedAs('define a project data file')
    ->default(__DIR__ . '/sample/cms.yaml')
    ->map(function ($data) {
        return $data;
    });

//目标路径
$cmd->option('t')
    ->aka('target')
    ->describedAs('define a target directory, default is : ' . TAR_ROOT_PATH)
    ->default(TAR_ROOT_PATH)
    ->map(function ($target) {
        return $target;
    });

//进行创建
$builder = new \generator\Builder([
    'config' => $cmd['config'],
    'data' => $cmd['data'],
    'target' => $cmd['target']
]);
$builder->run();
