#!/usr/bin/env php
<?php
/**
 * wa-craft/generator-php 
 */

/**
 * TODO v3.0.0 处理流程
 * 定义全局常量
 * 装载程序代码
 * 处理命令行参数
 * 初始化并运行程序
 * 增加中间件
 * 增加事件
 * 修改命令行方式
 */
/* 定义全局常量 */
define('SRC_PATH', __DIR__ . '/src');
define('PACKAGE_PATH', __DIR__ . '/pkg');
define('TAR_ROOT_PATH', __DIR__ . '/deploy');
define('VIEW_PATH', 'webapp/view');
define('VERSION', '3.0.0 alpha1');
define('RESOURCE_PATH', __DIR__ . '/resource');

/* 装载程序代码 */

/* 自动运行 composer 下载安装第三方程序 */
if (!file_exists(__DIR__ . "/vendor/autoload.php"))
    shell_exec('composer update');
require __DIR__ . "/vendor/autoload.php";

//设置命令
$cmd = new \Commando\Command();

$cmd->option()
    ->description('A command line toolkit to build MVC scaffold for thinkphp v6.*');

//配置文件
$cmd->option('c')
    ->aka('config')
    ->describedAs('define a configuration file, default is : ./src/config.php')
    ->default(__DIR__ . '/src/config.php')
    ->map(function ($config) {
        return $config;
    });

//项目
$cmd->option('p')
    ->aka('project')
    ->describedAs('define a project project file')
    ->default(__DIR__ . '/sample/cms.yaml')
    ->map(function ($project) {
        return $project;
    });

//目标路径
$cmd->option('t')
    ->aka('target')
    ->describedAs('define a target directory, default is : ' . TAR_ROOT_PATH)
    ->default(TAR_ROOT_PATH)
    ->map(function ($target) {
        return $target;
    });

//目标路径
$cmd->option('e')
    ->aka('debug')
    ->describedAs('enable or disable debug information: ')
    ->default(TRUE)
    ->map(function ($debug) {
        return $debug;
    });

//进行创建
$builder = new \generator\Builder([
    'config' => $cmd['config'],
    'project' => $cmd['project'],
    'target' => $cmd['target']
]);
$builder->run();
