DROP TABLE IF EXISTS `{{APP_NAME}}_{{MODEL_NAME}}`;
CREATE TABLE IF NOT EXISTS `{{APP_NAME}}_{{MODEL_NAME}}` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
{{FIELD_LOOP}}
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='{{MODULE_NAME}} {{MODEL_COMMENT}}表';